parameters:
  projectDirectory: ''

jobs:
- job: BuildAndTestProject
  displayName: 'Build & Test Project'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '18.x'
    
  - script: |
      cd ${{ parameters.projectDirectory }}
      npm install
    displayName: 'Install dependencies'
    
  - script: |
      cd ${{ parameters.projectDirectory }}
      npm run build
    displayName: 'Build Node App'
    
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'
    inputs:
      PathtoPublish: '${{ parameters.projectDirectory }}/build'
      ArtifactName: 'react-app'
      publishLocation: 'Container'
    