name: 'team-mapper-web_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)'

retention:
  days: 60
  minimumToKeep: 50
  deleteBuildRecord: true
  deleteTestResults: true

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - src/team-mapper-web/*
      - .azure/pipelines/node/*
      - .azure/pipelines/shared/*
      - .azure/pipelines/team-mapper-web.yaml

stages:
- stage: BuildAndPublish
  jobs:
  - template: node/build-project-template.yaml
    parameters:
      jobName: 'BuildAndPublishDockerImage'
      projectDirectory: 'src/team-mapper-web'
      sonarProjectKey: 'Team-Mapper-Web'
      sonarOrganization: 'pleasurendhlovudev'

  - template: shared/docker-build-template.yaml
    parameters:
      jobName: 'BuildAndPublishDockerImage'
      dependsOn: BuildAndTestProject
      dockerfilePath: 'src/team-mapper-web/Dockerfile'
      repositoryPath: 'pleasurendhlovudev'
      dockerImageName: 'team-mapper-web'

  - template: shared/run-security-tests.yaml
    parameters:
      jobName: 'RunSecurityTests'
      dependsOn: 'BuildAndPublishDockerImage'
      runOwaspZapTests: false
      dockerImage: 'team-mapper-web'
      target: 'src/team-mapper-api'

- stage: HelmChart
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - template: shared/deploy-helm-chart.yaml
    parameters:
      jobName: 'DeployHelmChart'
      helmChart: 'team-mapper-web'
