name: '$(Build.SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - .azure/pipelines/database/*
      - .azure/pipelines/team-mapper-database.yaml

variables:
- group: Team-Mapper 

stages:
- stage: BuildAndPublish
  jobs:
  - template: database/build-project-template.yaml
    parameters:
      jobName: 'Build'
      project: 'team-mapper-infrastructure'
      startUpProject: 'team-mapper-api'

  - template: .net/run-architecture-tests-template.yaml
    parameters:
      testProject: 'test/architecture-tests/team-mapper-architecture-tests/team-mapper-architecture-tests.csproj'
      buildConfiguration: 'Release'

  - template: shared/run-security-tests.yaml
    parameters:
      jobName: 'RunSecurityTests'
      dependsOn: 'Build'
      projectName: src/team-mapper-api/team-mapper-api.csproj
      projectFolder: 'team-mapper-api'
      runOwaspZapTests: false
      dockerImage: 'team-mapper-api'
      target: 'src/team-mapper-api'
      nvd_api_key: '$(NVD_API_KEY)'

# - stage: DeployDatabase
#   condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
#   jobs:
#   - template: database/deploy-database-template.yaml
#     parameters:
#       job: 'Deploy'
#       project: 'team-mapper-infrastructure'
#       startUpProject: 'team-mapper-api'

