name: 'team-mapper-web_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - src/team-mapper-web/*

stages:
- stage: BuildAndPublish
  jobs:
  - template: node/build-project-template.yaml
    parameters:
      projectDirectory: 'src/team-mapper-web'
