name: '$(Build.SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - .azure/pipelines/database/*
      - .azure/pipelines/team-mapper-database.yaml

stages:
- stage: BuildAndPublish
  jobs:
  - template: database/build-project-template.yaml
    parameters:
      jobName: 'Build'
      project: 'team-mapper-infrastructure'
      startUpProject: 'team-mapper-api'

  - template: shared/run-security-tests.yaml
    parameters:
      jobName: 'RunSecurityTests'
      dependsOn: 'Build'
      projectName: src/team-mapper-api/team-mapper-api.csproj
      projectFolder: 'team-mapper-api'
      runOwaspZapTests: true
      dockerImage: 'team-mapper-api'
      target: 'src/team-mapper-api'

- stage: DeployDatabase
  # condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - template: database/deploy-database-template.yaml
    parameters:
      job: 'Deploy'
      project: 'team-mapper-infrastructure'
      startUpProject: 'team-mapper-api'

