name: 'team-mapper-web_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - src/team-mapper-web/*

stages:
- stage: BuildAndPublish
  jobs:
  - template: node/build-project-template.yaml
    parameters:
      projectDirectory: 'src/team-mapper-web'

  - template: shared/docker-build-template.yaml
    parameters:
      dependsOn: BuildAndTestProject
      jobName: 'BuildAndPublishDockerImage'
      dockerfilePath: 'src/team-mapper-web/Dockerfile'
      repositoryPath: 'pleasurendhlovudev'
      dockerImageName: 'team-mapper-web'
