name: 'team-mapper-web_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - src/team-mapper-web/*
      - .azure/pipelines/node/*
      - .azure/pipelines/shared/*
      - .azure/pipelines/team-mapper-web.yaml

stages:
- stage: BuildAndPublish
  jobs:
  - template: node/build-project-template.yaml
    parameters:
      jobName: 'BuildAndPublishDockerImage'
      projectDirectory: 'src/team-mapper-web'
      sonarProjectKey: 'Team-Mapper-Web'
      sonarOrganization: 'pleasurendhlovudev'

  - template: shared/docker-build-template.yaml
    parameters:
      jobName: 'BuildAndPublishDockerImage'
      dependsOn: BuildAndTestProject
      dockerfilePath: 'src/team-mapper-web/Dockerfile'
      repositoryPath: 'pleasurendhlovudev'
      dockerImageName: 'team-mapper-web'
