name: 'team-mapper-api_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - src/team-mapper-api/*
      - .azure/pipelines/.net/*
      - .azure/pipelines/shared/*
      - .azure/pipelines/team-mapper-api.yaml

stages:
- stage: BuildAndPublish
  jobs:
  # - template: .net/build-project-template.yaml
  #   parameters:
  #     job: 'Build'
  #     solution: 'src/team-mapper-api/team-mapper-api.csproj'
  #     buildConfiguration: 'Release'
  #     artifactName: 'team-mapper-api-artifact'
  #     testProjects: 'test/unit-tests/team-mapper-api-unit-tests/team-mapper-api-unit-tests.csproj'
  #     sonarProjectKey: 'Team-Mapper-Api'
  #     sonarOrganization: 'pleasurendhlovudev'

  # - template: .net/run-integration-tests-docker-template.yaml
  #   parameters:
  #     jobName: 'DockerComposeRun'
  #     dependsOn: Build
  #     dockerComposeFile: 'test/integration-tests/team-mapper-api-integration-tests-docker/docker-compose.yaml'
  #     testProjects: 'test/integration-tests/team-mapper-api-integration-tests-docker/team-mapper-api-integration-tests-docker.csproj'

  # - template: shared/docker-build-template.yaml
  #   parameters:
  #     jobName: 'BuildAndPublishDockerImage'
  #     dependsOn: DockerComposeRun
  #     dockerfilePath: 'src/team-mapper-api/Dockerfile'
  #     repositoryPath: 'pleasurendhlovudev'
  #     dockerImageName: 'team-mapper-api'

  - template: shared/run-security-tests.yaml
    parameters:
      jobName: 'RunSecurityTests'
      # dependsOn: 'BuildAndPublishDockerImage'
      projectName: src/team-mapper-api/team-mapper-api.csproj
