name: 'team-mapper-database_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - .azure/pipelines/database/*
      - .azure/pipelines/team-mapper-database.yaml

stages:
- stage: BuildAndPublish
  jobs:
  - template: database/build-project-template.yaml
    parameters:
      job: 'Build'
      Project: 'src/team-mapper-infrastructure/team-mapper-infrastructure'
      startUpProject: 'src/team-mapper-api/team-mapper-api'

- stage: DeployDatabase
  jobs:
  - template: database/deploy-database-template.yaml
