name: 'team-mapper-database_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - src/team-mapper-database/*
      - .azure/pipelines/database/*
      - .azure/pipelines/team-mapper-database.yaml

stages:
- stage: BuildAndPublish
  jobs:
  - template: database/build-project-template.yaml
    parameters:
      job: 'Build'
      projectDirectory: 'src/team-mapper-database'
      sonarProjectKey: 'Team-Mapper-Database'
      sqlProject: 'src/team-mapper-database/team-mapper-database.sqlproj'
      testProject: 'test/unit-tests/team-mapper-database-unit-tests/team-mapper-api-database-tests.csproj'
