services:
  team-mapper-api:
    build:
      context: .
      dockerfile: src/team-mapper-api/Dockerfile
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  team-mapper-web:
    build:
      context: .
      dockerfile: src/team-mapper-web/Dockerfile
    depends_on:
      - team-mapper-api
    ports:
      - 3001:3001
