parameters:
  jobName: ''
  dependsOn: ''
  helmChart: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: 'Build and Publish Helm Chart'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: HelmInstaller@1
    displayName: 'Install Helm'
    inputs:
      helmVersionToInstall: 'latest'

  - task: Powershell@2
    displayName: 'Lint Helm Chart'
    inputs:
      targetType: 'inline'
      script: |
        helm lint .\.k8s\${{ parameters.helmChart }} \ --values .\.k8s\${{ parameters.helmChart }}\values.yaml  --strict