parameters:
  jobName: ''
  dependsOn: ''
  helmChart: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: 'Build and Publish Helm Chart'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: HelmInstaller@1
    displayName: 'Install Helm'
    inputs:
      helmVersionToInstall: 'latest'

  - task: Powershell@2
    displayName: 'Lint Helm Chart'
    inputs:
      targetType: 'inline'
      script: |
        helm lint $(Build.SourcesDirectory)/.k8s/${{ parameters.helmChart }} --values $(Build.SourcesDirectory)/.k8s/${{ parameters.helmChart }}/values.yaml  --strict

  - task: Powershell@2
    displayName: 'Package Helm Chart'
    inputs:
      targetType: 'inline'
      script: |
        helm package $(Build.SourcesDirectory)/.k8s/${{ parameters.helmChart }} --destination $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Helm Chart Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: ${{ parameters.helmChart }}-helm-chart
      publishLocation: 'Container'