parameters:
  jobName: ''
  dependsOn: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: 'Build and Publish Helm Chart'
  # dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: HelmInstaller@1
    displayName: 'Install Helm'
    inputs:
      helmVersionToInstall: 'latest'