parameters:
  jobName: 'RunSecurityTests'
  dependsOn: ''
  projectName: ''
  projectFolder: ''
  runOwaspZapTests: true

jobs:
- job: ${{ parameters.jobName }}
  displayName: 'Run Security Tests'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - ${{ if eq(parameters.runOwaspZapTests, true) }}:
    - script: |
        echo Installing OWASP Dependency Check...
        wget http://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip
        unzip dependency-check-6.1.6-release.zip
      displayName: 'Install OWASP Dependency Check'

  - ${{ if eq(parameters.runOwaspZapTests, true) }}:
    - script: |
        echo Running OWASP Dependency Check...
        ./dependency-check/bin/dependency-check.sh --project ${{ parameters.projectName }} --scan "$(Build.SourcesDirectory)/src/${{ parameters.projectFolder }}/" --out "$(Build.ArtifactStagingDirectory)/dependency-check-report"
      displayName: 'Run OWASP Dependency Check'

  - ${{ if eq(parameters.runOwaspZapTests, true) }}:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/dependency-check-report'
        artifact: 'OWASPDependencyCheckReport'