parameters:
  jobName: 'RunSecurityTests'
  dependsOn: ''
  projectName: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: 'Build and Publish Docker Image'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: |
        echo Installing OWASP Dependency Check...
        wget http://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
        unzip dependency-check-12.1.0-release.zip
      displayName: 'Install OWASP Dependency Check'

    - script: |
        echo Running OWASP Dependency Check...
        ./dependency-check/bin/dependency-check.sh --project ${{ parameters.projectName }} --scan "$(Build.SourcesDirectory)/" --out "$(Build.ArtifactStagingDirectory)/dependency-check-report"
      displayName: 'Run OWASP Dependency Check'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/dependency-check-report'
        artifact: 'OWASPDependencyCheckReport'