parameters:
  projectDirectory: ''
  sonarProjectKey: ''
  sonarOrganization: 'pleasurendhlovudev'
  sonarServiceConnection: 'SonarCloudConnection'
  sqlProject: ''
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildAndTestProject
  displayName: 'Build & Test Project'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: SonarCloudPrepare@3
    displayName: 'Prepare SonarCloud Analysis'
    inputs:
      SonarCloud: ${{ parameters.sonarServiceConnection }}
      organization: ${{ parameters.sonarOrganization }}    
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: ${{ parameters.sonarProjectKey }}
      cliProjectName: ${{ parameters.sonarProjectKey }}
      extraProperties: |
        sonar.sources=${{ parameters.projectDirectory }}
        sonar.exclusions=node_modules/**,**/*.test.js
        sonar.javascript.lcov.reportPaths=coverage/lcov.info

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.x'

  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: restore
      restoreSolution: ${{ parameters.sqlProject }}

  - task: VSBuild@1
    displayName: 'Build .sqlproj'
    inputs:
      solution: ${{ parameters.sqlProject }}
      msbuildArgs: '/p:Configuration=${{ parameters.buildConfiguration }}'
      platform: ${{ parameters.buildPlatform }}
      configuration: ${{ parameters.buildConfiguration }}

  - task: CopyFiles@2
    displayName: 'Copy DACPAC to artifact staging directory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**\bin\${{ parameters.buildConfiguration }}\*.dacpac'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: dacpac'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'dacpac'
      publishLocation: 'Container'

  - task: SonarCloudAnalyze@3
    displayName: 'SonarCloud Analyze'

  # - task: SonarCloudPublish@3
  #   inputs:
  #     pollingTimeoutSec: '300'
  #   displayName: 'SonarCloud Publish'
    