parameters:
  dependsOn: ''
  buildConfiguration: 'Release'
  project: ''
  startUpProject: ''

jobs:
- job: BuildDatabaseProject
  displayName: 'Build & Test Project'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'windows-latest'

  steps:
    - task: UseDotNet@2
      displayName: 'Install .Net 9.0'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: PowerShell@2
      displayName: 'Install EFCore Tools'
      inputs:
        targetType: 'inline'
        script: 'dotnet tool install --global dotnet-ef'

    - task: DotNetCoreCLI@2
      displayName: 'Restore Projects'
      inputs:
        command: 'restore'
        projects: '${{ parameters.project }}.csproj;${{ parameters.startUpProject }}.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Run Build'
      inputs:
        command: 'build'
        projects: '${{ parameters.project }}.csproj;${{ parameters.startUpProject }}.csproj'
        arguments: '--configuration ${{ parameters.buildConfiguration }}'

    - task: PowerShell@2
      displayName: 'Install EFCore Tools'
      inputs:
        targetType: 'inline'
        script: 'dotnet tool install --global dotnet-ef'

    - task: PowerShell@2
      displayName: 'Run EF Migrations'
      inputs:
        targetType: 'inline'
        script: |
          dotnet ef migrations add $(Build.BuildNumber) --project ${{ parameters.Project }} --startup-project ${{ parameters.startUpProject }}--output-dir Migrations