parameters:
  dependsOn: ''
  artifactName: 'dacpac'

jobs:
- job: DeployDatabase
  displayName: 'Deploy Database'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadBuildArtifacts@1
    displayName: 'Download Artifact: dacpac'
    inputs:
      buildType: 'current'   # downloads artifacts from current build
      artifactName: ${{ parameters.artifactName }}
      downloadPath: '$(Pipeline.Workspace)/downloaded'

  - task: Powershell@2
    displayName: 'List downloaded files'
    inputs:
      targetType: 'inline'
      script: |
        ls -R $(Pipeline.Workspace)/downloaded    