parameters:
  dependsOn: ''
  artifactName: 'drop'

jobs:
- job: DeployDatabase
  displayName: 'Deploy Database'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadBuildArtifacts@1
    displayName: 'Download Artifact: dacpac'
    inputs:
      buildType: 'current'   # downloads artifacts from current build
      artifactName: ${{ parameters.artifactName }}
      downloadPath: '$(Pipeline.Workspace)/downloaded'

  - script: ls -R $(Pipeline.Workspace)/downloaded
    displayName: 'List downloaded files'
    