parameters:
  project: ''
  buildConfiguration: 'Release'

jobs:
- job: PublishNuget
  displayName: 'Publish NuGet Package'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore Project'
    inputs:
      command: 'restore'
      projects: '${{ parameters.project }}'

  - task: DotNetCoreCLI@2
    displayName: 'Run Build'
    inputs:
      command: 'build'
      projects: '${{ parameters.project }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }}'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet Tool'
    inputs:
      versionSpec: 

  - task: NuGetCommand@2
    displayName: 'Pack NuGet Packages'
    inputs:
      command: 'pack'
      packagesToPack: '${{ parameters.project }}'
      versioningScheme: 'off'

  - task: NuGetCommand@2
    displayName: 'Publish NuGet Packages'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
