parameters:
  testProject: ''
  buildConfiguration: 'Release'

jobs:
- job: ArchitectureTests
  displayName: 'Run Architecture Tests'
  pool:
    vmImage: 'windows-latest'

  steps:
    - task: UseDotNet@2
      displayName: 'Install .Net 9.0'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
    
    - task: DotNetCoreCLI@2
      displayName: 'Restore Architecture Test Project'
      inputs:
        command: 'restore'
        projects: '${{ parameters.testProject }}'

    - task: DotNetCoreCLI@2
      displayName: 'Build Architecture Test Project'
      inputs:
        command: 'build'
        projects: '${{ parameters.testProject }}'
        arguments: '--configuration ${{ parameters.buildConfiguration }} --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Run Architecture Tests'
      inputs:
        command: 'test'
        projects: '${{ parameters.testProject }}'
        arguments: '--configuration ${{ parameters.buildConfiguration }} --no-build --logger trx --results-directory $(Common.TestResultsDirectory)'

    - task: PublishTestResults@2
      displayName: 'Publish Architecture Test Results'
      condition: always()
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        searchFolder: '$(Common.TestResultsDirectory)'
        mergeTestResults: true
        failTaskOnFailedTests: true
        testRunTitle: 'Architecture Tests Results'